eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka/
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:postgresql://local-database:5432/articles_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: validate
