eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comments_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: validate
