version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: ./config-server
        image: nc-news-project/config-server:latest
        ports:
            - 9090:9090
        networks:
            - emp-network
        environment:
            SPRING_PROFILES_ACTIVE: remote
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery-service
        ports:
            - 9091:9091
        networks:
            - emp-network
        depends_on:
            - config-server
        environment:
            SPRING_PROFILES_ACTIVE: prod
    articles-service:
        container_name: articles-service
        build:
            context: ./articles-service
        image: nc-news-project/articles-service:latest
        ports:
            - 8080:8080
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: prod
    comments-service:
        container_name: comments-service
        build:
            context: ./comments-service
        image: nc-news-project/comments-service:latest
        ports:
            - 8081:8081
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: prod
    website:
        container_name: website
        build:
            context: ./website
        image: nc-news-project/website:latest
        ports:
            - 80:80
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
    gateway-service:
        container_name: gateway-service
        build:
            context: ./gateway-service
        image: nc-news-project/gateway-service:latest
        ports:
            - 8084:8084
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: prod
networks:
    emp-network:
        driver: bridge
