version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: ./config-server
            args:
                JAR_FILE: target/config-server-0.0.1-SNAPSHOT.jar
        image: nc-news-project/config-server:latest
        expose:
            - 9090
        ports:
            - 9090:9090
        networks:
            - emp-network
        environment:
            SPRING_PROFILES_ACTIVE: remote
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery-service
            args:
                JAR_FILE: target/discovery-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/discovery-service:latest
        expose:
            - 9091
        ports:
            - 9091:9091
        networks:
            - emp-network
        depends_on:
            - config-server
        environment:
            SPRING_PROFILES_ACTIVE: prod
    articles-service:
        container_name: articles-service
        build:
            context: ./articles-service
            args:
                JAR_FILE: target/articles-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/articles-service:latest
        expose:
            - 8080
        ports:
            - 8080:8080
            - 5005:5005 # remote debugging port
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        command:
            "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: prod
    comments-service:
        container_name: comments-service
        build:
            context: ./comments-service
            args:
                JAR_FILE: target/comments-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/comments-service:latest
        expose:
            - 8081
        ports:
            - 8081:8081
            - 5006:5006 # remote debugging port
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        command:
            "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: prod
    website:
        container_name: website
        build:
            context: ./website
        image: nc-news-project/website:latest
        expose:
            - 80
        ports:
            - 80:80
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
    gateway-service:
        container_name: gateway-service
        build:
            context: ./gateway-service
            args:
                JAR_FILE: target/gateway-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/gateway-service:latest
        expose:
            - 8084
        ports:
            - 8084:8084
        networks:
            - emp-network
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: prod
networks:
    emp-network:
        driver: bridge
