version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: ./config-server
            args: 
                JAR_FILE: target/config-server-0.0.1-SNAPSHOT.jar
        image: nc-news-project/config-server:latest
        expose:
            - 9090
        ports:
            - 9090:9090
        networks:
            - emp-network
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery-service
            args: 
                JAR_FILE: target/discovery-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/discovery-service:latest
        expose:
            - 9091
        ports:
            - 9091:9091
        networks:
            - emp-network
    articles-service:
        container_name: articles-service
        build:
            context: ./articles-service
            args:
                JAR_FILE: target/articles-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/articles-service:latest
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:9090"}}}}'
        expose:
            - 8080
        ports:
            - 8080:8080
        networks:
            - emp-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
        depends_on:
            - config-server
            - discovery-service
        command: ["./wait-for-it.sh", "localhost:9091"]
        logging:
            driver: json-file
    website:
        container_name: website
        build:
            context: ./website
        image: nc-news-project/website:latest
        expose:
            - 80
        ports:
            - 80:80
        networks:
            - emp-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
        depends_on:
            - config-server
            - discovery-service
#        command: ["./wait-for-it.sh", "localhost:9091"]
        logging:
            driver: json-file
    gateway-service:
        container_name: gateway-service
        build:
            context: ./gateway-service
            args:
                JAR_FILE: target/gateway-service-0.0.1-SNAPSHOT.jar
        image: nc-news-project/gateway-service:latest
        expose:
            - 8084
        ports:
            - 8084:8084
        networks:
            - emp-network
        links:
            - discovery-service:discovery-service
        depends_on:
            - discovery-service
        logging:
            driver: json-file
networks:
    emp-network:
        driver: bridge
