version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: ./config-server
        image: nc-news-project/config-server:latest
        ports:
            - 9090:9090
        environment:
            SPRING_PROFILES_ACTIVE: native
        volumes:
            - ./config-repo:/etc/configs
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery-service
        image: nc-news-project/discovery-service:latest
        ports:
            - 9091:9091
        depends_on:
            - config-server
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_CLOUD_CONFIG_URI: http://config-server:9090
    articles-service:
        container_name: articles-service
        build:
            context: ./articles-service
        image: nc-news-project/articles-service:latest
        ports:
            - 8080:8080
            - 5005:5005 # remote debugging port
        entrypoint:
            "java -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar /app.jar"
        depends_on:
            - config-server
            - discovery-service
            - local-database
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_CLOUD_CONFIG_URI: http://config-server:9090
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9091/eureka/
            SPRING_DATASOURCE_URL: jdbc:postgresql://local-database:5432/articles_db
    auth-server:
        container_name: auth-server
        build:
            context: ./auth-server
        image: nc-news-project/auth-server:latest
        ports:
            - 9999:9999
            - 5007:5007 # remote debugging port
        entrypoint:
            "java -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5007 -jar /app.jar"
        depends_on:
            - config-server
            - discovery-service
            - local-database
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_CLOUD_CONFIG_URI: http://config-server:9090
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9091/eureka/
            SPRING_DATASOURCE_URL: jdbc:postgresql://local-database:5432/auth_db
    comments-service:
        container_name: comments-service
        build:
            context: ./comments-service
        image: nc-news-project/comments-service:latest
        ports:
            - 8081:8081
            - 5006:5006 # remote debugging port
        entrypoint:
            "java -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 -jar /app.jar"
        depends_on:
            - config-server
            - discovery-service
            - local-database
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_CLOUD_CONFIG_URI: http://config-server:9090
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9091/eureka/
            SPRING_DATASOURCE_URL: jdbc:postgresql://local-database:5432/comments_db?stringtype=unspecified
    website:
        container_name: website
        build:
            context: ./website
        image: nc-news-project/website:latest
        ports:
            - 4200:4200
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
    gateway-service:
        container_name: gateway-service
        build:
            context: ./gateway-service
        image: nc-news-project/gateway-service:latest
        ports:
            - 8084:8084
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_CLOUD_CONFIG_URI: http://config-server:9090
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9091/eureka/
    local-database:
        container_name: local-database
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
          - $PWD/local-db:/docker-entrypoint-initdb.d
    mail-service:
        container_name: mail-service
        build:
            context: ./mail-service
        image: nc-news-project/mail-service:latest
        ports:
            - 9955:9955
        depends_on:
            - config-server
            - discovery-service
            - local-database
        logging:
            driver: json-file
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_CLOUD_CONFIG_URI: http://config-server:9090
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9091/eureka/
            SPRING_DATASOURCE_URL: jdbc:postgresql://local-database:5432/mail_db
            SPRING_MAIL_HOST: fake-smtp
            SPRING_MAIL_PORT: 5025
            SPRING_GATEWAY_URL: http://gateway-service:8084

    fake-smtp:
        container_name: fake-smtp
        image: gessnerfl/fake-smtp-server
        ports:
            - 5025:5025
            - 5080:5080
            - 5081:5081
#TODO: add auth and mail service configurations
