server:
  port: 9955
spring:
  mail:
    host: localhost
    port: 5025
    username: random-username
    password: random-password
    properties:
      mail:
        from: mail@netcracker-news-project.com
        smtp:
          auth: true
          starttls.enable: false