server:
  port: 9090
---
spring:
  profiles: native
  cloud.config.server:
        native:
          searchLocations: /etc/configs
---
spring:
  profiles: remote
  cloud.config.server:
    git:
      uri: https://litsov@bitbucket.org/litsov/netcracker-project-config-repo.git
